---

- name: Remove user from webservers
  hosts: webservers
  become: true
  tasks:
  - name: Delete user from webservers
    user:
      name: "{{ item }}"
      state: absent
      remove: yes
    with_list:
    - Ajit
    - Rahul
    - Jambu