---

- name: Install Tomcat to target nodes
  hosts: all
  become: yes
  tasks:
  - name: Install Java on RedHat severs
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"
  
  - name: Install Java on Ubuntu server
    apt:
      name: openjdk-11-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: Download Package
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.82/bin/apache-tomcat-9.0.82.tar.gz
      dest: /opt

  - name: unzip package
    unarchive:
      src: /opt/apache-tomcat-9.0.82.tar.gz
      dest: /opt
      remote_src: yes

  - name: Add Executable permissions to startup.sh file
    file:
      path: /opt/apache-tomcat-9.0.82/bibb.startup.sh
      mode: 0777

  - name: Start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.82/bin