--- 

- name: Install and Start httpd on all servers
  hosts: all
  become: true
  tasks:
  - name: Install httpd using yum
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    tags: Install_apache

  - name: Start the httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: Start_service

  - name: Install apache2 on Ubuntu server
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: Install_apache

  - name: Start apache2 on Ubuntu server
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    tags: Start_service
    
  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
