---

- name: Playbook to install and start the httpd service
  hosts: webservers
  become: true
  tasks:
  - name: Install httpd using yum
    yum:
      name: httpd
      state: installed

  - name: Start the httpd service
    service:
      name: httpd
      state: started
