---

- name: Playbook to install tomcat server on target node
  hosts: all
  become: true
  tasks:
  # Task to insall java on Redhat and Amazon linus server using yum module
  - name: Install java
    yum:
      name: java
      state: installed
    when: ansible_os_family ==  "RedHat"
   
  # Task to install Java on Ubuntu server using apt module
  - name: Install java on Ubuntu
    apt:
      name: openjdk-11-jdk
      state: present
    when: ansible_os_family ==  "Debian"

  # Download tomcat package
  - name: Download package 
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.82/bin/apache-tomcat-9.0.82.tar.gz
      dest: /opt
  # Unzip the package using unarchive
  - name: unzip apache package
    unarchive:
      src: /opt/apache-tomcat-9.0.82.tar.gz
      dest: /opt
      remote_src: yes

  # add permissions to startup.sh file and give full permissions
  - name: add execution permissions on startup.sh file
    file:
      path: /opt/apache-tomcat-9.0.82/bin/startup.sh
      mode: 0777

  # Start the tomcat services using shell module. change directory as well.
  - name: Start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.82/bin
