---
# handlers file for setup_httpd
- name: Start httpd
  service:
    name: httpd
    state: started

- name: Start apache2
  service:
    name: apache2
    state: started

- name: Restart httpd service on RedHat servers
  service:
    name: httpd
    state: restarted 